name: build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            platform: linux/amd64
          - arch: riscv64
            platform: linux/riscv64

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup qemu
        uses: docker/setup-qemu-action@v3

      - name: build pkgs
        run: |
          mkdir -p output_packages
          chmod 777 output_packages
          
          docker run --rm -v ${{ github.workspace }}:/work -w /work --platform ${{ matrix.platform }} alpine:latest sh -c '
            apk add alpine-sdk sudo
            adduser -D builder && addgroup builder abuild
            echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
            
            mkdir -p /home/builder/.abuild
            PUBKEY=$(ls /work/keys/*.pub | head -n 1)
            PUBKEY_NAME=$(basename "$PUBKEY")
            PRIVKEY_NAME="${PUBKEY_NAME%.pub}"
            
            echo "${{ secrets.ALPINE_PRIVKEY }}" > /home/builder/.abuild/$PRIVKEY_NAME
            cp "$PUBKEY" /home/builder/.abuild/$PUBKEY_NAME
            cp "$PUBKEY" /etc/apk/keys/$PUBKEY_NAME
            echo "PACKAGER_PRIVKEY=/home/builder/.abuild/$PRIVKEY_NAME" > /home/builder/.abuild/abuild.conf
            
            chown -R builder:builder /home/builder/.abuild
            chown -R builder:builder /work
            
            for pkg_dir in /work/main/*; do
              if [ -f "$pkg_dir/APKBUILD" ]; then
                echo "building in $pkg_dir for ${{ matrix.arch }}..."
                su builder -c "cd $pkg_dir && abuild -r -c" || exit 1
              fi
            done
            
            if [ -d /home/builder/packages ]; then
              cp -a /home/builder/packages/* /work/output_packages/
              echo "build successful. artifacts:"
              find /work/output_packages/ -type f
            else
              echo "/home/builder/packages not found. This is fine."
              exit 0
            fi
          '

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages-${{ matrix.arch }}
          path: output_packages/

  publish:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: download and merge artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: packages-*
            path: public/
            merge-multiple: true

        - name: prepare keys
          run: |
            mkdir -p public/keys
            cp keys/*.pub public/keys/
          
            echo "gh-pages:"
            find public/ -type f

        - name: deploy to gh-pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public
            force_orphan: true
